[package]
name = "atomics_and_locks"
version = "0.1.0"
edition = "2021"

[lib]
name = "r"
path = "src/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
